### ISSUE TITLE
Problem installing acumos in the first place.

### ISSUE THREAD

**Issue by pelekhs** [peschue/ai4eu-sudoku#1]
Hello, 

I have two questions:

1. I tried to install acumos in a local cluster using the [z2a installation guide](https://docs.acumos.org/en/latest/submodules/system-integration/docs/z2a/installation-guide.html) so as to locally reproduce your sudoku example. I get the following error when running the final step ./1-acumos.sh:

LAST DEPLOYED: Tue Mar  9 04:55:05 2021
NAMESPACE: acumos-dev1
STATUS: deployed
REVISION: 1
TEST SUITE: None
Installing Acumos Portal FE chart ....
Error: Ingress.extensions "portal-fe-ingress" is invalid: spec.tls[0].secretName: Invalid value: "tls-cert-secretName": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

That is the result of **kubectl get pods -A** after this error:

NAMESPACE              NAME                                                                                                 READY   STATUS      RESTARTS   AGE
acumos-dev1            acumos-docker-785ff98f6f-kb5dr                                                         2/2     Running     1          14m
acumos-dev1            acumos-k8s-cds-6dfbf58f7b-rxbqs                                                       2/2     Running     0          14m
acumos-dev1            acumos-k8s-portal-be-cdcccc795-7tvfd                                               0/2     Pending     0          14m
acumos-dev1            acumos-k8s-portal-fe-c78c8ff7-4r4vx                                                   2/2     Running     0          14m
acumos-dev1            acumos-nexus-sonatype-nexus-7fbc77b8f7-z88gq                              1/1     Running     0          21m
acumos-dev1            acumos-proxy-6cc854c5df-dbm8h                                                       1/1     Running     0          14m
acumos-dev1            elasticsearch-78c79cbb46-44gqq                                                          3/3     Running     0          14m
acumos-dev1            kibana-54cfd8c96b-5rtqc                                                                       1/1     Running     0          14m
acumos-dev1            license-profile-editor-license-profile-editor-helm-chart-5zx25n           1/1     Running     0          14m
acumos-dev1            license-rtu-editor-license-rtu-editor-helm-chart-84cf6c957hhz44        1/1     Running     0          14m
acumos-dev1            license-usage-manager-lum-helm-6bddb6bd77-l5pfr                           1/1     Running     0          14m
acumos-dev1            license-usage-manager-postgresql-0                                                      1/1     Running     0          14m
acumos-dev1            logstash-9fd47554b-4pm8b                                                                    1/1     Running     0          14m
acumos-dev1            nexus-proxy-nginx-59cc5649df-7dk5j                                                     1/1     Running     0          18m
acumos-dev1            pyauth-66c97d66bc-f6rmq                                                                      1/1     Running     0          18m
acumos-dev1            pyauth-66c97d66bc-kwdmq                                                                    1/1     Running     0          18m
acumos-dev1            xxxxxx-master-0                                                                                        1/1     Running     0          17m
acumos-dev1            xxxxxx-slave-0                                                                                           1/1     Running     0          17m
ingress-nginx          ingress-nginx-admission-create-4bbdd                                                    0/1     Completed   0          81m
ingress-nginx          ingress-nginx-admission-patch-bjqhw                                                     0/1     Completed   2          81m
ingress-nginx          ingress-nginx-controller-c7c5dfc9f-bl9bw                                               1/1     Running     0          81m
kube-system            coredns-74ff55c5b-8f84d                                                                        1/1     Running     0          81m
kube-system            coredns-74ff55c5b-msvxt                                                                       1/1     Running     0          81m
kube-system            etcd-kind-acumos-control-plane                                                            1/1     Running     0          81m
kube-system            kindnet-8npsz                                                                                         1/1     Running     0          81m
kube-system            kindnet-jss8t                                                                                           1/1     Running     0          81m
kube-system            kindnet-kgztp                                                                                        1/1     Running     0          81m
kube-system            kindnet-pt8pk                                                                                        1/1     Running     0          81m
kube-system            kube-apiserver-kind-acumos-control-plane                                          1/1     Running     0          81m
kube-system            kube-controller-manager-kind-acumos-control-plane                        1/1     Running     0          81m
kube-system            kube-proxy-54fwh                                                                                 1/1     Running     0          81m
kube-system            kube-proxy-957wt                                                                                 1/1     Running     0          81m
kube-system            kube-proxy-n9g6f                                                                                 1/1     Running     0          81m
kube-system            kube-proxy-pgrlq                                                                                1/1     Running     0          81m
kube-system            kube-scheduler-kind-acumos-control-plane                                      1/1     Running     0          81m
kubernetes-dashboard   dashboard-metrics-scraper-7b59f7d4df-w6t9q                           1/1     Running     0          81m
kubernetes-dashboard   kubernetes-dashboard-7fc7d58b86-4x7ln                                  1/1     Running     0          81m
local-path-storage     local-path-provisioner-78776bfc44-67lzr                                        1/1     Running     0          81m
metallb-system         controller-fb659dc8-4bqcv                                                               1/1     Running     0          81m
metallb-system         speaker-2kq27                                                                                  1/1     Running     0          81m
metallb-system         speaker-dsl47                                                                                    1/1     Running     0          80m
metallb-system         speaker-nwl5d                                                                                   1/1     Running     0          80m
metallb-system         speaker-qj6wm                                                                                  1/1     Running     0          81m

I am not sure if this is the right place to ask but there is no option to raise any issues [here](https://github.com/acumos/system-integration).

2. Except for that is it mandatory to locally install acumos (BYOC) so as to run your example?

Thanks in advance!

**Comment by peschue** [comment]
Hello! Thank you for your interest.

The current state of this example is intended as a preparation to run this from Acumos. In other words, the current repository state does **not** require Acumos to run.

Another issue is that, whatever will happen, **you will never need to install Acumos locally**.

AI4EU modifies Acumos to a certain extent do make it suitable for AI4EU Experiments, which will be much more than what Acumos was intended to do originally. This modified AI4EU Acumos will permit you to download a package that contains scripts for deploying your solution in a kubernetes environment.

So for executing AI4EU experiments, you never need to install Acumos, you only need a kubernetes environment, for example minikube. To use this repository, please follow the steps in [README.md](https://github.com/peschue/ai4eu-sudoku/blob/master/README.md).

Does this answer your questions?
