### ISSUE TITLE
grpc._channel._InactiveRpcError, status = StatusCode.UNIMPLEMENTED

### ISSUE THREAD

**Issue by ndrewtl** [peschue/ai4eu-sudoku#3]
Hi Peter! I hope you're doing well. I have been working to set up this project on my own local device, and followed the following steps:

1. I installed `grpcio` and `grpcio-tools` via [pipenv](https://pipenv.pypa.io/en/latest/) and entered my virtualenv shell.
2. I ran the following four commands:
```py
$ ./helper.py build-protobufs
$ ./helper.py build
$ ./helper.py run detached
$ ./helper.py orchestrate
```

When I did this, I was able to see the three containers up and running, as well as the orchestrator entering its loop. When I visited `localhost:8000` I then saw the sudoku grid displayed as expected. However, when I clicked a square (for instance, inserting a 5 in the top-center square), the orchestrator threw this exception:

```sh
INFO:root:calling OneshotSolver.solve() with parameters number_of_answers: 2

ERROR:root:exception (retrying after 2 seconds): Traceback (most recent call last):
  File "/home/username/work/ai4eu-sudoku/orchestrator/orchestrator.py", line 59, in main
    aspresult = aspsolver_stub.solve(solverjob)
  File "/home/username/.local/share/virtualenvs/ai4eu-sudoku-ordygZ5C/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/username/.local/share/virtualenvs/ai4eu-sudoku-ordygZ5C/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "Method not found!"
        debug_error_string = "{"created":"@1633690462.721976925","description":"Error received from peer ipv6:[::1]:8003","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Method not found!","grpc_status":12}"
>

INFO:root:calling SudokuGUI.requestSudokuEvaluation() with empty dummy
```

Additionally, the sudoku grid did not perform the desired functions (e.g. it did not display any red when inserting two 5's in the same row).

I am not sure if I didn't configure this project in the correct way. I currently am having difficulty accessing the website, and so I did not complete the onboarding process. However, it is my understanding that in this case, the `helper.py` script can run the entire thing locally without having to onboard online? Let me know if I am getting something wrong, and how I can go about setting up the project correctly. Thanks!

**Comment by peschue** [comment]
You are right, `helper.py` is supposed to allow you to run the whole example without AI4EU Acumos/Kubernetes, just using docker. It should work. I will try exactly what you did and get back to you.

**Comment by ndrewtl** [comment]
Thanks. Were you able to reproduce the error? I removed all my docker images and tried again and got the same thing

**Comment by peschue** [comment]
I am sorry but I did not have the time yet to investigate.

**Comment by peschue** [comment]
I was able to reproduce the problem. Working on it.

**Comment by peschue** [comment]
Please try again with the latest main branch, I renamed a method only in the ASP Solver component but not in the orchestrator, and this caused the problems. Should be fixed now. Please let me know if it works for you.

edit1: if you do git pull you will need to rerun `./helper.py build-protobufs` before `./helper.py orchestrate`.

edit2: no need to recompile docker images. the change is in the orchestrator only.

**Comment by ndrewtl** [comment]
It works! So cool! Thanks so much.

**Comment by peschue** [comment]
You are welcome! Happy to help!
